# SSH
alias nik="ssh -Y dadriaan@nikara.rap.ucar.edu"
alias raneb="ssh -Y dadriaan@raneb.rap.ucar.edu"
alias djoser="ssh -Y dadriaan@djoser.rap.ucar.edu"
alias sonbef="ssh -Y dadriaan@sonbef.rap.ucar.edu"
alias huni="ssh -Y dadriaan@huni.rap.ucar.edu"
alias khaba="ssh -Y dadriaan@khaba.rap.ucar.edu"
alias tuvok="ssh -Y dadriaan@tuvok.rap.ucar.edu"
alias ahmose="ssh -Y dadriaan@ahmose.rap.ucar.edu"
alias horus="ssh -Y dadriaan@horus.rap.ucar.edu"
alias redoubt="ssh -Y dadriaan@redoubt.rap.ucar.edu"
alias etage="ssh -Y dadriaan@etage.rap.ucar.edu"
alias mizu="ssh -Y dadriaan@mizu.rap.ucar.edu"
alias floyd="ssh -Y dadriaan@floyd.rap.ucar.edu"
alias eyewall="ssh -Y dadriaan@eyewall.rap.ucar.edu"
alias dakota="ssh -Y dadriaan@dakota.rap.ucar.edu"
alias kiowa="ssh -Y dadriaan@kiowa.rap.ucar.edu"
alias doohan="ssh -Y dadriaan@doohan.rap.ucar.edu"
alias jlab="ssh -Y dadriaan@jlab-nima1.rap.ucar.edu"
alias cessna="ssh -Y dadriaan@cessna.rap.ucar.edu"
alias web="ssh -Y dadriaan@content.rap.ucar.edu"
alias satdev2="ssh -Y dadriaan@satdev2.rap.ucar.edu"
alias grebe="ssh -Y dadriaan@grebe.rap.ucar.edu"
alias mandan="ssh -Y dadriaan@mandan.rap.ucar.edu"
alias radia="ssh -Y dadriaan@radia.rap.ucar.edu"

# CONDA
alias cenv="conda info --envs"
alias cend="conda deactivate"
alias cload="conda activate"
alias clist="conda list"
alias cinit="source ~/.condainit"

# GIT
alias token="ssh -Y dadriaan@cessna.rap.ucar.edu 'cat ~/.git_token'"

# LINUX
alias ll="ls -lh"
alias shell="echo $SHELL"
alias la="ls -lha"
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias mkdir="mkdir -p"
alias du="du -sh"
alias mat="matlab -nojvm -nodisplay -nosplash -r"
alias dotfiles="ls -a | grep '^\.'"
alias vim="vim -X"
